### ISSUE TITLE
ConcurrentModificationException can occur when indexing documents 

### ISSUE THREAD

**Issue by tommyktech** [TomSearch/elasticsearch-japanese-suggester#1]
I came across the following exception when I tried to index a suggest document "ｋ". 
I seldom see this exception, not always. 

<pre>
[2015-12-27 01:51:57,437][DEBUG][action.bulk              ] [Ultragirl] [suggest_sample][2] failed to execute bulk item (index) index {[suggest_sample][test][AVHfNC18Jv11Ywtn3og7], source[{"suggest":"ｋ"}]}
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
        at java.util.ArrayList$Itr.next(ArrayList.java:831)
        at org.elasticsearch.analysis.KeystrokeUtil$Node.keyStrokes(KeystrokeUtil.java:137)
        at org.elasticsearch.analysis.KeystrokeUtil$KeystrokeBuilder.keyStrokes(KeystrokeUtil.java:107)
        at org.elasticsearch.analysis.KeystrokeUtil.toKeyStrokes(KeystrokeUtil.java:51)
        at org.elasticsearch.analysis.KuromojiSuggestTokenizer.reset(KuromojiSuggestTokenizer.java:112)
        at org.apache.lucene.analysis.TokenStreamToAutomaton.toAutomaton(TokenStreamToAutomaton.java:110)
        at org.apache.lucene.search.suggest.analyzing.XAnalyzingSuggester.toFiniteStrings(XAnalyzingSuggester.java:928)
        at org.elasticsearch.search.suggest.completion.AnalyzingCompletionLookupProvider.toFiniteStrings(AnalyzingCompletionLookupProvider.java:400)
        at org.elasticsearch.search.suggest.completion.CompletionTokenStream.incrementToken(CompletionTokenStream.java:63)
        at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:612)
        at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:344)
        at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:300)
        at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:232)
        at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:458)
        at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1363)
        at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1142)
        at org.elasticsearch.index.engine.InternalEngine.innerCreateNoLock(InternalEngine.java:427)
        at org.elasticsearch.index.engine.InternalEngine.innerCreate(InternalEngine.java:369)
        at org.elasticsearch.index.engine.InternalEngine.create(InternalEngine.java:341)
        at org.elasticsearch.index.shard.IndexShard.create(IndexShard.java:517)
        at org.elasticsearch.index.engine.Engine$Create.execute(Engine.java:789)
        at org.elasticsearch.action.support.replication.TransportReplicationAction.executeIndexRequestOnPrimary(TransportReplicationAction.java:1073)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:338)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:131)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.performOnPrimary(TransportReplicationAction.java:579)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase$1.doRun(TransportReplicationAction.java:452)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
</pre>

**Comment by tommyktech** [comment]
fixed
